# Generated by Django 6.0.6 on 2026-06-13 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Write about your day, feelings, study experience...')),
                ('mood_score', models.PositiveIntegerField(choices=[(1, '😢 Terrible'), (2, '😟 Bad'), (3, '😕 Not Great'), (4, '😐 Okay'), (5, '🙂 Decent'), (6, '😊 Good'), (7, '😄 Great'), (8, '🤩 Amazing'), (9, '🌟 Fantastic'), (10, '🔥 On Top of the World')], default=5)),
                ('mood_label', models.CharField(blank=True, max_length=50)),
                ('emotions', models.CharField(blank=True, help_text='Comma-separated emotion tags', max_length=200)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_insights', models.TextField(blank=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('dominant_emotion', models.CharField(blank=True, max_length=50)),
                ('burnout_risk', models.FloatField(blank=True, null=True)),
                ('encouragement', models.TextField(blank=True)),
                ('coping_suggestions', models.TextField(blank=True)),
                ('is_analyzed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_score', models.PositiveIntegerField(choices=[(1, '😢 Terrible'), (2, '😟 Bad'), (3, '😕 Not Great'), (4, '😐 Okay'), (5, '🙂 Decent'), (6, '😊 Good'), (7, '😄 Great'), (8, '🤩 Amazing'), (9, '🌟 Fantastic'), (10, '🔥 On Top of the World')], default=5)),
                ('energy_level', models.PositiveIntegerField(default=5, help_text='1-10 energy scale')),
                ('anxiety_level', models.PositiveIntegerField(default=5, help_text='1-10 anxiety scale')),
                ('motivation_level', models.PositiveIntegerField(default=5, help_text='1-10 motivation scale')),
                ('quick_note', models.CharField(blank=True, max_length=280)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='StressTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('academic', 'Academic Pressure'), ('social', 'Social Issues'), ('family', 'Family Pressure'), ('health', 'Health Concerns'), ('sleep', 'Sleep Issues'), ('comparison', 'Peer Comparison'), ('time', 'Time Management'), ('self_doubt', 'Self-Doubt'), ('perfectionism', 'Perfectionism'), ('other', 'Other')], max_length=30)),
                ('trigger_detail', models.CharField(max_length=200)),
                ('severity', models.PositiveIntegerField(default=5, help_text='1-10 severity scale')),
                ('identified_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stress_triggers', to='journal.journalentry')),
            ],
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', '-created_at'], name='journal_jou_user_id_1ad335_idx'),
        ),
        migrations.AddIndex(
            model_name='moodlog',
            index=models.Index(fields=['user', '-logged_at'], name='journal_moo_user_id_d1745c_idx'),
        ),
        migrations.AddIndex(
            model_name='stresstrigger',
            index=models.Index(fields=['entry', 'trigger_type'], name='journal_str_entry_i_76016a_idx'),
        ),
    ]
