# Generated by Django 6.0.6 on 2026-06-13 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('avg_mood', models.FloatField(blank=True, null=True)),
                ('avg_anxiety', models.FloatField(blank=True, null=True)),
                ('avg_energy', models.FloatField(blank=True, null=True)),
                ('total_entries', models.PositiveIntegerField(default=0)),
                ('ai_summary', models.TextField(blank=True)),
                ('key_patterns', models.TextField(blank=True, help_text='JSON array')),
                ('recommendations', models.TextField(blank=True, help_text='JSON array')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_end'],
                'unique_together': {('user', 'week_start')},
            },
        ),
    ]
