# Generated by Django 6.0.6 on 2026-06-13 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MindfulnessExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('breathing', 'Breathing'), ('grounding', 'Grounding'), ('meditation', 'Meditation'), ('body_scan', 'Body Scan'), ('visualization', 'Visualization'), ('quick_reset', 'Quick Reset')], max_length=20)),
                ('description', models.TextField()),
                ('duration_minutes', models.PositiveIntegerField(default=5)),
                ('steps', models.TextField(help_text='JSON array of step strings')),
                ('emoji', models.CharField(default='🧘', max_length=10)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
            ],
            options={
                'ordering': ['category', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='WellnessAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('burnout', 'Burnout Risk'), ('mood_drop', 'Mood Decline'), ('streak', 'Journal Streak'), ('positive', 'Positive Trend'), ('tip', 'Wellness Tip'), ('reminder', 'Check-in Reminder')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical'), ('positive', 'Positive')], default='info', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('recommended_action', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='wellness_we_user_id_96a502_idx')],
            },
        ),
    ]
