# Generated by Django 6.0.6 on 2026-06-13 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('NEET', 'NEET'), ('JEE', 'JEE (Main/Advanced)'), ('CUET', 'CUET'), ('CAT', 'CAT'), ('GATE', 'GATE'), ('UPSC', 'UPSC'), ('BOARD_10', 'Board Exams (Class 10)'), ('BOARD_12', 'Board Exams (Class 12)'), ('OTHER', 'Other')], default='JEE', max_length=20)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('daily_study_hours', models.PositiveIntegerField(default=6)),
                ('goals', models.TextField(blank=True, help_text='What are your goals for this exam?')),
                ('avatar_emoji', models.CharField(default='🎓', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
