from django.db import models
from django.contrib.auth.models import User


class WellnessAlert(models.Model):
    """Proactive wellness alerts generated by the system."""
    ALERT_TYPES = [
        ('burnout', 'Burnout Risk'),
        ('mood_drop', 'Mood Decline'),
        ('streak', 'Journal Streak'),
        ('positive', 'Positive Trend'),
        ('tip', 'Wellness Tip'),
        ('reminder', 'Check-in Reminder'),
    ]
    SEVERITY_CHOICES = [
        ('info', 'Info'),
        ('warning', 'Warning'),
        ('critical', 'Critical'),
        ('positive', 'Positive'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='wellness_alerts')
    alert_type = models.CharField(max_length=20, choices=ALERT_TYPES)
    severity = models.CharField(max_length=20, choices=SEVERITY_CHOICES, default='info')
    title = models.CharField(max_length=100)
    message = models.TextField()
    recommended_action = models.TextField(blank=True)
    is_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['user', 'is_read', '-created_at']),
        ]

    def __str__(self):
        return f"{self.get_alert_type_display()}: {self.title}"

    @property
    def icon(self):
        icons = {
            'burnout': '🔥', 'mood_drop': '📉', 'streak': '🎯',
            'positive': '🌟', 'tip': '💡', 'reminder': '🔔',
        }
        return icons.get(self.alert_type, '📋')

    @property
    def color(self):
        colors = {
            'info': 'blue', 'warning': 'orange',
            'critical': 'red', 'positive': 'green',
        }
        return colors.get(self.severity, 'blue')


class MindfulnessExercise(models.Model):
    """Library of mindfulness exercises."""
    CATEGORY_CHOICES = [
        ('breathing', 'Breathing'),
        ('grounding', 'Grounding'),
        ('meditation', 'Meditation'),
        ('body_scan', 'Body Scan'),
        ('visualization', 'Visualization'),
        ('quick_reset', 'Quick Reset'),
    ]

    title = models.CharField(max_length=100)
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)
    description = models.TextField()
    duration_minutes = models.PositiveIntegerField(default=5)
    steps = models.TextField(help_text="JSON array of step strings")
    emoji = models.CharField(max_length=10, default='🧘')
    difficulty = models.CharField(max_length=20, default='beginner',
                                  choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')])

    class Meta:
        ordering = ['category', 'difficulty']

    def __str__(self):
        return f"{self.emoji} {self.title}"
